// Mock data for job listings
export const mockJobs = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: {
      name: "TechCorp",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "Remote",
    salary: "$120,000 - $150,000",
    type: "Full-time",
    category: "Engineering",
    createdAt: new Date("2023-05-15"),
  },
  {
    id: "2",
    title: "UX/UI Designer",
    company: {
      name: "DesignHub",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "New York, NY",
    salary: "$90,000 - $110,000",
    type: "Full-time",
    category: "Design",
    createdAt: new Date("2023-05-18"),
  },
  {
    id: "3",
    title: "Backend Engineer",
    company: {
      name: "ServerStack",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "San Francisco, CA",
    salary: "$130,000 - $160,000",
    type: "Full-time",
    category: "Engineering",
    createdAt: new Date("2023-05-20"),
  },
  {
    id: "4",
    title: "Product Manager",
    company: {
      name: "ProductLabs",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "Remote",
    salary: "$110,000 - $140,000",
    type: "Full-time",
    category: "Product",
    createdAt: new Date("2023-05-22"),
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: {
      name: "CloudOps",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "Austin, TX",
    salary: "$125,000 - $155,000",
    type: "Full-time",
    category: "Engineering",
    createdAt: new Date("2023-05-25"),
  },
  {
    id: "6",
    title: "Marketing Specialist",
    company: {
      name: "GrowthGenius",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "Chicago, IL",
    salary: "$80,000 - $100,000",
    type: "Full-time",
    category: "Marketing",
    createdAt: new Date("2023-05-28"),
  },
  {
    id: "7",
    title: "Data Scientist",
    company: {
      name: "DataDriven",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "Remote",
    salary: "$140,000 - $170,000",
    type: "Full-time",
    category: "Data",
    createdAt: new Date("2023-06-01"),
  },
  {
    id: "8",
    title: "Customer Success Manager",
    company: {
      name: "ClientFirst",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "Boston, MA",
    salary: "$85,000 - $105,000",
    type: "Full-time",
    category: "Customer Support",
    createdAt: new Date("2023-06-03"),
  },
  {
    id: "9",
    title: "Mobile Developer",
    company: {
      name: "AppWorks",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "Seattle, WA",
    salary: "$115,000 - $145,000",
    type: "Full-time",
    category: "Engineering",
    createdAt: new Date("2023-06-05"),
  },
  {
    id: "10",
    title: "Content Writer",
    company: {
      name: "ContentCraft",
      logo: "/placeholder.svg?height=40&width=40",
    },
    location: "Remote",
    salary: "$70,000 - $90,000",
    type: "Contract",
    category: "Marketing",
    createdAt: new Date("2023-06-08"),
  },
]

// Mock data for job postings in the dashboard
export const mockJobPostings = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    applications: 24,
    postedDate: "May 15, 2023",
    expiresAt: "Jun 15, 2023",
    status: "active",
  },
  {
    id: "2",
    title: "UX/UI Designer",
    applications: 18,
    postedDate: "May 18, 2023",
    expiresAt: "Jun 18, 2023",
    status: "active",
  },
  {
    id: "3",
    title: "Backend Engineer",
    applications: 12,
    postedDate: "May 20, 2023",
    expiresAt: "Jun 20, 2023",
    status: "active",
  },
  {
    id: "4",
    title: "Product Manager",
    applications: 0,
    postedDate: "Draft",
    expiresAt: "N/A",
    status: "draft",
  },
  {
    id: "5",
    title: "DevOps Engineer",
    applications: 0,
    postedDate: "Draft",
    expiresAt: "N/A",
    status: "draft",
  },
  {
    id: "6",
    title: "Marketing Specialist",
    applications: 32,
    postedDate: "Apr 28, 2023",
    expiresAt: "May 28, 2023",
    status: "expired",
  },
  {
    id: "7",
    title: "Data Scientist",
    applications: 15,
    postedDate: "Apr 01, 2023",
    expiresAt: "May 01, 2023",
    status: "expired",
  },
]

